### ISSUE TITLE
Interface modifications

### ISSUE THREAD

**Issue by josiah-tesfu** [EdgePi-Cloud/node-red-edgepi-adc#4]
- Some fields have colons while others don't. They should all be consistent.
- Rpc Server --> RPC Server
- The placeholder text, "IP Address" under the RPC Server field should indicate an option for entering the hostname, e.g. "IP Address/ Hostname"
- Remove the word "node" from the node name. No other node-RED nodes have it and it's a bit redundant.
- After selecting the RTD option for the Read field, currently shows both ADC1 and ADC2 under the ADC field, even though only ADC2 is clickable. Should show only ADC2.

**Comment by farzadpanahi** [comment]
> Remove the word "node" from the node name. No other node-RED nodes have it and it's a bit redundant.

where is this "node" in the node name? what are our node names at the moment? what is the guideline from node-red?

**Comment by josiah-tesfu** [comment]
> > Remove the word "node" from the node name. No other node-RED nodes have it and it's a bit redundant.
> 
> where is this "node" in the node name? what are our node names at the moment? what is the guideline from node-red?

@farzadpanahi The node is named "edgepi-adc-node". To be in line with the way other nodes in Node-RED are named, it would be named just "edgepi-adc". There doesn't seem to be a guideline for naming from Node-RED though.

**Comment by farzadpanahi** [comment]
there is this guideline for naming packages -> https://nodered.org/docs/creating-nodes/packaging#naming

where is the node name defined? is it different from the package name?
